import { NextResponse } from 'next/server';

export async function GET() {
    const data = [
        {
            id: 80,
            judul: "Makna Cinta, Rizky Febrian",
            link: "https://www.youtube.com/watch?v=rois6RucjF0",
            tahun: "2020 September 4",
            playlist : [
                "b",
                "2", "h", "5", "8", "9",
            ],
            added: "30 Maret 2021",
        },
        {
            id: 79,
            judul: "Celebrity, UI",
            link: "https://www.youtube.com/watch?v=Uu_-mdjXVVI",
            tahun: "2021 Januari 27",
            playlist : [
                "b",
                "1", "5", "h", "7", "10",
            ],
            added: "30 Maret 2021",
        },
        {
            id: 78,
            judul: "Hold On, Justin Bieber",
            link: "https://www.youtube.com/watch?v=4ldRN59GMD8",
            tahun: "2021 Maret 5",
            playlist : [
                "b",
                "2", "5", "7", "60",
            ],
            added: "30 Maret 2021",
        },
        {
            id: 77,
            judul: "To the Bone, Pamungkas",
            link: "https://www.youtube.com/watch?v=VKIpVVPbzgw",
            tahun: "1993 April 14",
            playlist : [
                "b",
                "3", "h", "8", "60",
            ],
            added: "30 Maret 2021",
        },
        {
            id: 76,
            judul: "Kota, Dere",
            link: "https://www.youtube.com/watch?v=d9bVO1Hi_JY",
            tahun: "2020 Oktober 28",
            playlist : [
                "b",
                "1", "1", "7", "9",
            ],
            added: "25 Maret 2021",
        },
        {
            id: 75,
            judul: "Head & Heart (feat. MNEK), Joel Corry, MNEK",
            link: "https://www.youtube.com/watch?v=wy_4ORZU9ik",
            tahun: "2020 Juli 3",
            playlist : [
                "b",
                "2", "g", "k", "60",
            ],
            added: "23 Maret 2021",
        },
        {
            id: 74,
            judul: "Love In My Pocket, Rich Brian",
            link: "https://www.youtube.com/watch?v=OPhQtD2k2WY",
            tahun: "2020 Juli 9",
            playlist : [
                "b",
                "2", "a", "k", "60",
            ],
            added: "15 Maret 2021",
        },
        {
            id: 73,
            judul: "Girl In The Mirror - I, Sophia Grace, Silentó",
            link: "https://www.youtube.com/watch?v=k2GxzFMi4Dw",
            tahun: "2017 Januari 20",
            playlist : [
                "b",
                "2", "5", "7", "60",
            ],
            added: "14 Maret 2021",
        },
        {
            id: 72,
            judul: "Genius (feat. Sia, Diplo, and Labrinth), Sia, Diplo, Labrinth, LSD",
            link: "https://www.youtube.com/watch?v=fuZCvYgzWZ4",
            tahun: "2018 Mei 3",
            playlist : [
                "b",
                "2", "d", "8", "60",
            ],
            added: "14 Maret 2021",
        },
        {
            id: 71,
            judul: "Panini, Lil Nas X",
            link: "https://www.youtube.com/watch?v=b0P4dPhxUGA",
            tahun: "2019 Juni 20",
            playlist : [
                "b",
                "2", "d", "8", "60",
            ],
            added: "14 Maret 2021",
        },
        {
            id: 70,
            judul: "Old Town Road, Lil Nas X",
            link: "https://www.youtube.com/watch?v=wje0gdzlGus",
            tahun: "2019 Juli 19",
            playlist : [
                "b",
                "2", "6", "d", "8", "60",
            ],
            added: "14 Maret 2021",
        },
        {
            id: 69,
            judul: "Leave The Door Open, Bruno Mars, Anderson.Paak, Silk Sonic",
            link: "https://www.youtube.com/watch?v=_A3lQdNY5yw",
            tahun: "2021 Maret 5",
            added: "11 Maret 2021",
            playlist : [
                "b",
                "1", "a", "7", "60",
            ],
        },
        {
            id: 68,
            judul: "Lose, NIKI",
            link: "https://www.youtube.com/watch?v=J5eE1YYinTM",
            tahun: "2020 Agustus 13",
            added: "11 Maret 2021",
            playlist : [
                "b",
                "1", "4", "7", "60",
            ],
        },
        {
            id: 67,
            judul: "Melukis Senja, Budi Doremi",
            link: "https://www.youtube.com/watch?v=fd0iauNvJVo",
            tahun: "2020 Juni 24",
            added: "11 Maret 2021",
            playlist : [
                "b",
                "1", "5", "7", "9",
            ],
        },
        {
            id: 66,
            judul: "One Only, Pamungkas",
            link: "https://www.youtube.com/watch?v=jFtYHwrPhpM",
            tahun: "2018 Juli 15",
            added: "11 Maret 2021",
            playlist : [
                "b",
                "3", "4", "k", "60",
            ],
        },
        {
            id: 65,
            judul: "Heather, Conan Gray",
            link: "https://www.youtube.com/watch?v=bj3HnriNscw",
            tahun: "2020 September 4",
            added: "11 Maret 2021",
            playlist : [
                "b",
                "3", "4", "7", "60",
            ],
        },
        {
            id: 64,
            judul: "Copines, Aya Nakamura ",
            link: "https://www.youtube.com/watch?v=vvW9KP-JQ0U",
            tahun: "2018 Agustus 24",
            added: "11 Maret 2021",
            playlist : [
                "b",
                "2", "h", "7", "59",
            ],
        },
        {
            id: 63,
            judul: "Slow Ride - Edit, Foghat",
            link: "https://www.youtube.com/watch?v=ktXYnjGwpMc",
            tahun: "1975 September 15",
            added: "9 Maret 2021",
            playlist : [
                "b",
                "3", "j", "8", "60",
            ],
        },
        {
            id: 62,
            judul: "Heartbreak Anniversary, GIVĒON",
            link: "https://www.youtube.com/watch?v=NEuIfbkYbwc",
            tahun: "2020 Februari 21",
            added: "8 Maret 2021",
            playlist : [
                "b",
                "3", "4", "8", "60",
            ],
        },
        {
            id: 61,
            judul: "Before I Forget, Slipknot",
            link: "https://www.youtube.com/watch?v=ssg1Ak9PMn4",
            tahun: "2009 Oktober 27",
            added: "8 Maret 2021",
            playlist : [
                "b",
                "2", "i", "8", "60",
            ],
        },
        {
            id: 60,
            judul: "Dancing in My Room, 347aidan",
            link: "https://www.youtube.com/watch?v=_EIbX6ZF_J4",
            tahun: "2020 Oktober 26",
            added: "7 Maret 2021",
            playlist : [
                "b",
                "3", "h", "8", "60",
            ],
        },
        {
            id: 59,
            judul: "Sugar Daddy, Qveen Herby",
            link: "https://www.youtube.com/watch?v=6h6lDT732iM",
            tahun: "2020 Mei 26",
            added: "7 Maret 2021",
            playlist : [
                "b",
                "2", "d", "7", "60",
            ],
        },
        {
            id: 58,
            judul: "Hadal Ahbek, Issam Alnajjar",
            link: "https://www.youtube.com/watch?v=kR5X9z5eHQA",
            tahun: "2020 September 27",
            added: "7 Maret 2021",
            playlist : [
                "b",
                "3", "h", "8", "48",
            ],
        },
        {
            id: 57,
            judul: "NO BATIDÃO, ZXKAI, slxughter",
            link: "https://www.youtube.com/watch?v=xRwrdaNteGU",
            tahun: "2025 Oktober 29",
            added: "14 Januari 2026",
            playlist : [
                "b",
                "2", "e", "8", "124", "6",
            ],
        },
        {
            id: 56,
            judul: "Love Story (Taylor’s Version), Taylor Swift",
            link: "https://www.youtube.com/watch?v=C6SBAJLlv9c",
            tahun: "2008 September 12",
            added: "7 Maret 2021",
            playlist : [
                "b", "c",
                "3", "h", "8", "60",
            ],
        },{
            id: 55,
            judul: "Papi Chulo, Octavian, Skepta",
            link: "https://www.youtube.com/watch?v=ABAoyB16RJs",
            tahun: "2020 Maret 13",
            added: "7 Maret 2021",
            playlist : [
                "b",
                "2", "d", "8", "60",
            ],
        },
        {
            id: 54,
            judul: "Hurts So Good, Astrid S",
            link: "https://www.youtube.com/watch?v=mGij0v2SOVg",
            tahun: "2016 Mei 6",
            added: "7 Maret 2021",
            playlist : [
                "b",
                "3", "4", "7", "60", "1",
            ],
        },
        {
            id: 53,
            judul: "Mood (feat. Ian dior), 24kGoldn, iann dior",
            link: "https://www.youtube.com/watch?v=FaKK34QDBKw",
            tahun: "2020 Agustus 5",
            added: "5 Maret 2021",
            playlist : [
                "b",
                "2", "5", "7", "60", "d",
            ],
        },
        {
            id: 52,
            judul: "Katakan Saja, Khifnu",
            link: "https://www.youtube.com/watch?v=zqz7TOtDgWE",
            tahun: "2020 Maret 1",
            added: "4 Maret 2021",
            playlist : [
                "b",
                "1", "h", "7", "9",
            ],
        },
        {
            id: 51,
            judul: "Snowman, Sia",
            link: "https://www.youtube.com/watch?v=KL_g3CS-Ffs",
            tahun: "2017 November 9",
            added: "4 Maret 2021",
            playlist : [
                "b",
                "3", "h", "7", "60",
            ],
        },
        {
            id: 50,
            judul: "It’s My Life, Bon Jovi",
            link: "https://www.youtube.com/watch?v=smvXQO7Lmxk",
            tahun: "2000 Mei 23",
            added: "17 Januari 2021",
            playlist : [
                "b",
                "2", "6", "8", "60", "i",
            ],
        },
        {
            id: 49,
            judul: "Happy Pills, Weathers",
            link: "https://www.youtube.com/watch?v=Y7Hpn-iYJq0",
            tahun: "2016 Juni 03",
            added: "4 Januari 2021",
            playlist : [
                "b",
                "2", "5", "8", "60",
            ],
        },
        {
            id: 48,
            judul: "Head on My Shoulder, David Alexander",
            link: "https://www.youtube.com/watch?v=aQ5B4tKLh8M",
            tahun: "2020 Februari 14",
            added: "4 Januari 2021",
            playlist : [
                "b",
                "3", "4", "8", "60", "h",
            ],
        },
        {
            id: 47,
            judul: "Montagem Supersonic, KHAOS, Jmilton, Mc Jajá",
            link: "https://www.youtube.com/watch?v=ugTlOuU99MM",
            tahun: "2025 Juli 04",
            added: "21 Desember 2025",
            playlist : [
                "b",
                "2", "e", "6", "8", "124",
            ],
        },
        {
            id: 46,
            judul: "Corduroy Dreams, Rex Orange County",
            link: "https://www.youtube.com/watch?v=qpKrzv22o04",
            tahun: "2016 November 07",
            added: "25 Desember 2020",
            playlist : [
                "b",
                "3", "5", "8", "60", "h",
            ],
        },
        {
            id: 45,
            judul: "ill come back to you (feat. Sarcastic Sounds & Rxseboy)",
            link: "https://www.youtube.com/watch?v=I78gRj2UHWM",
            tahun: "2020 Mei 29",
            added: "23 Desember 2020",
            playlist : [
                "b",
                "2", "4", 'd', "8", "60", "h",
            ],
        },
        {
            id: 44,
            judul: "When we were 16, Rxseboy, Powfu, Mishaal Tamer",
            link: "https://www.youtube.com/watch?v=36rUC4bCKmc",
            tahun: "2019 Oktober 06",
            added: "22 Desember 2020",
            playlist : [
                "b",
                "2", '4', "d", "8", "60", "h",
            ],
        },
        {
            id: 43,
            judul: "Figurinha - Ao Vivo, Douglas & Vinicius, MC Bruninho",
            link: "https://www.youtube.com/watch?v=FkiEvrIdRUM",
            tahun: "2020 Juni 12",
            added: "22 Desember 2020",
            playlist : [
                "b",
                "3", "a", "7", "124",
            ],
        },
        {
            id: 42,
            judul: "Holding On, Ian Dior",
            link: "https://www.youtube.com/watch?v=1LNdE9QTjSM",
            tahun: "2020 November 20",
            added: "19 Desember 2020",
            playlist : [
                "b",
                "2", "4", "8", "60", "h",
            ],
        },
        {
            id: 41,
            judul: "ACELERADA, sma$her, MXZI",
            link: "https://www.youtube.com/watch?v=qvaTvGSEIcg",
            tahun: "2025 Juni 27",
            added: "21 Desember 2025",
            playlist : [
                "b",
                "2", "e", "6", "8", "124",
            ],
        },
        {
            id: 40,
            judul: "Fool, Cavetown",
            link: "https://www.youtube.com/watch?v=5jfZB3z9BZs",
            tahun: "2018 Januari 01",
            added: "13 Desember 2020",
            playlist : [
                "b",
                "3", "4", "8", "60",
            ],
        },
        {
            id: 39,
            judul: "18, Ian dior",
            link: "https://www.youtube.com/watch?v=eEhgHij7wfE",
            tahun: "2019 November 08",
            added: "8 Desember 2020",
            playlist : [
                "b",
                "2", "d", "8", "60", "h",
            ],
        },
        {
            id: 38,
            judul: "Bossa No Sé (feat. Jean Carter), Cuco, Jean Carter",
            link: "https://www.youtube.com/watch?v=82r8SD8NyXY",
            tahun: "2019 Mei 22",
            added: "29 November 2020",
            playlist : [
                "b",
                "2", "a", "8", "60",
            ],
        },
        {
            id: 37,
            judul: "Kingslayer (feat. BABYMETAL), Bring Me The Horizon, BABYMETAL",
            link: "https://www.youtube.com/watch?v=eLwa_QiCvvU",
            tahun: "2020 Oktober 30",
            added: "10 November 2020",
            playlist : [
                "b",
                "1", "6", "8", "60", "i",
            ],
        },
        {
            id: 36,
            judul: "Surrender, Natalie Taylor",
            link: "https://www.youtube.com/watch?v=MAgAlm4LqeA",
            tahun: "2015 Oktober 29",
            added: "27 Juli 2020",
            playlist : [
                "b",
                "3", "4", "7", "60",
            ],
        },
        {
            id: 35,
            judul: "Before You Go, Lewis Capaldi",
            link: "https://www.youtube.com/watch?v=94PTDMiQ6_k",
            tahun: "2019 November 19",
            added: "27 Juli 2020",
            playlist : [
                "b",
                "1", "4", "7", "60",
            ],
        },
        {
            id: 34,
            judul: "I Love You But I’m Letting Go, Pamungkas",
            link: "https://www.youtube.com/watch?v=Uk7_ZDCJ1_8",
            tahun: "2018 Juli 15",
            added: "22 Juni 2020",
            playlist : [
                "b",
                "3", "4", "8", "60", "9"
            ],
        },
        {
            id: 33,
            judul: "Savage Love (Laced - Siren Beat), Jawsh 658, Jason Derulo",
            link: "https://www.youtube.com/watch?v=Lp15hA9n8so",
            tahun: "2020 Juni 11",
            added: "22 Juni 2020",
            playlist : [
                "b",
                "2", "5", "8", "60", "h",
            ],
        },
        {
            id: 32,
            judul: "NO ERA AMOR - Slowed, DJ Asul",
            link: "https://www.youtube.com/watch?v=cYuDRDyBRRk",
            tahun: "2025 Mei 13",
            added: "2 Desember 2025",
            playlist : [
                "b",
                "2", "e", "8", "103",
            ],
        },
        {
            id: 31,
            judul: "Can We Kiss Forever?, Kina, Adriana Proenza",
            link: "https://www.youtube.com/watch?v=8RbahZCfgXk",
            tahun: "2018 Agustus 31",
            added: "20 Mei 2020",
            playlist : [
                "b",
                "3", "4", "8", "60",
            ],
        },
        {
            id: 30,
            judul: "Play Date, Melanie Martinez",
            link: "https://www.youtube.com/watch?v=HqKeWRPBOsI",
            tahun: "2015 Agustus 14",
            added: "20 Mei 2020",
            playlist : [
                "b",
                "2", "a", "8", "60", "h",
            ],
        },
        {
            id: 29,
            judul: "LATHI, Weird Genius, Sara Fajira",
            link: "https://www.youtube.com/watch?v=DJSPhdOcj6M",
            tahun: "2020 Februari 28",
            added: "20 Mei 2020",
            playlist : [
                "b",
                "1", "6", "8", "9", "301", "f",
            ],
        },
        {
            id: 28,
            judul: "Party Legends, Mobile Legends: Bang Bang",
            link: "https://www.youtube.com/watch?v=dmic4e4IdWA",
            tahun: "2020 April - Mei",
            added: "30 Juni 2020",
            playlist : [
                "b",
                "2", "5", "8", "60",
            ],
        },
        {
            id: 27,
            judul: "Peradaban, .Feast",
            link: "https://www.youtube.com/watch?v=EOsUSdze0tk",
            tahun: "2018 Juli 13",
            added: "13 Mei 2020",
            playlist : [
                "b",
                "3", "6", "8", "9",
            ],
        },
        {
            id: 26,
            judul: "Bali, Rich Brian, Guapdad 4000",
            link: "https://www.youtube.com/watch?v=uOnjowaxnlI",
            tahun: "2020 April",
            added: "16 April 2020",
            playlist : [
                "b",
                "2", "d", "8", "60",
            ],
        },
        {
            id: 25,
            judul: "Toosie Slide, Drake",
            link: "https://www.youtube.com/watch?v=Sxbs03nuBRE",
            tahun: "2020 April 03",
            added: "16 April 2020",
            playlist : [
                "b",
                "2", "a", "8", "60",
            ],
        },
        {
            id: 24,
            judul: "Don’t Start Now, Dua Lipa",
            link: "https://www.youtube.com/watch?v=6G07RP-DnaE",
            tahun: "2019 Oktober 31",
            added: "15 April 2020",
            playlist : [
                "b",
                "2", "5", "7", "60",
            ],
        },
        {
            id: 23,
            judul: "Rumah Ke Rumah, Hindia",
            link: "https://www.youtube.com/watch?v=zX7atb-_kvQ",
            tahun: "2019 November 29",
            added: "10 April 2020",
            playlist : [
                "b",
                "3", "4", "8", "9",
            ],
        },
        {
            id: 22,
            judul: "Tatu, Happy Asmara",
            link: "https://www.youtube.com/watch?v=5rw5X7_98eU",
            tahun: "2019 Juli",
            added: "30 Maret 2020",
            playlist : [
                "b",
                "2", "4", "8", "301", "f",
            ],
        },
        {
            id: 21,
            judul: "Lugu, Celine & Nadya",
            link: "https://www.youtube.com/watch?v=OluZLBnIpAg",
            tahun: "2018 Maret",
            added: "30 Maret 2020",
            playlist : [
                "b",
                "2", "5", "7", "9",
            ],
        },
        {
            id: 20,
            judul: "Bagaikan Langit, Potret",
            link: "https://www.youtube.com/watch?v=JTGUhj2qnhE",
            tahun: "1998",
            added: "30 Maret 2020",
            playlist : [
                "b",
                "2", "5", "8", "9", "h",
            ],
        },
        {
            id: 19,
            judul: "Happy, Skinnyfabs",
            link: "https://www.youtube.com/watch?v=kYzibhSWknc",
            tahun: "2019 Juli 5",
            added: "30 Maret 2020",
            playlist : [
                "b",
                "3", "4", "8", "60",
            ],
        },
        {
            id: 18,
            judul: "Tonight You Belong to Me, Eddie Vedder",
            link: "https://www.youtube.com/watch?v=ytuxo3aZtD4",
            tahun: "2011",
            added: "30 Maret 2020",
            playlist : [
                "b",
                "3", "a", "8", "60", "h",
            ],
        },
        {
            id: 17,
            judul: "COMETHRUE, JEREMY ZUCKER",
            link: "https://www.youtube.com/watch?v=jovxjsTkBeE",
            tahun: "2018 September 28",
            added: "30 Maret 2020",
            playlist : [
                "b",
                "3", "a", "8", "60",
            ],
        },
        {
            id: 16,
            judul: "DIA DELÍCIA slowed version, Nakama, ΣP",
            link: "https://www.youtube.com/watch?v=nPafxUt-XUE",
            tahun: "2025",
            added: "30 November 2025",
            playlist : [
                "b",
                "2", "e", "8", "124",
            ],
        },
        {
            id: 15,
            judul: "The Box, Roddy Ricch",
            link: "https://www.youtube.com/watch?v=2Ok95dyfwHI",
            tahun: "2019 Desember 6",
            added: "30 Maret 2020",
            playlist : [
                "b",
                "2", "d", "8", "60",
            ],
        },
        {
            id: 14,
            judul: "Tolong, Budi Doremi",
            link: "https://www.youtube.com/watch?v=UXmfPh5LjOY",
            tahun: "2018",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "3", "a", "7", "9", "h",
            ],
        },
        {
            id: 13,
            judul: "Psycho , Red Velvet",
            link: "https://www.youtube.com/watch?v=EAYvJ3E0ysw",
            tahun: "2019 Desember 23",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "1", "5", "8", "10", "h",
            ],
        },
        {
            id: 12,
            judul: "Waktu Yang Salah, Fiersa Besari",
            link: "https://www.youtube.com/watch?v=iyocjlk6z9E",
            tahun: "2014",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "3", "4", "8", "9"
            ],
        },
        {
            id: 11,
            judul: "Halu, Feby Putri",
            link: "https://www.youtube.com/watch?v=5qZJ6DJzcLE",
            tahun: "2019 Agustus 18",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "3", "4", "7", "9", "h",
            ],
        },
        {
            id: 10,
            judul: "It's You, Ali Gatie",
            link: "https://www.youtube.com/watch?v=a1obpxiMZHs",
            tahun: "2019?",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "3", "4", "8", "60", "h",
            ],
        },
        {
            id: 9,
            judul: "Any Song, ZICO",
            link: "https://www.youtube.com/watch?v=Qd0NqTEz2Qk",
            tahun: "2020",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "2", "d", "8", "10",
            ],
        },
        {
            id: 8,
            judul: "Nyaman, Andmesh",
            link: "https://www.youtube.com/watch?v=E_1SdECi8lg",
            tahun: "2019 November 22",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "3", "5", "7", "9", "h",
            ],
        },
        {
            id: 7,
            judul: "Roxanne, Arizona Zervas",
            link: "https://www.youtube.com/watch?v=96RZInZAD6Y",
            tahun: "2019 Oktober 10",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "2", "a", "8", "60", "h",
            ],
        },
        {
            id: 6,
            judul: "Memories, Maroon 5",
            link: "https://www.youtube.com/watch?v=Gqmo9jstTTU",
            tahun: "2019 September 20",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "3", "a", "8", "60", "h",
            ],
        },
        {
            id: 5,
            judul: "Someone You Loved, Lewis Capaldi",
            link: "https://www.youtube.com/watch?v=ywU6uYEmRfs",
            tahun: "2018 November 8",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "2", "4", "7", "60", "h",
            ],
        },
        {
            id: 4,
            judul: "Yummy, Justin Bieber",
            link: "https://www.youtube.com/watch?v=zD8dy-kj3qs",
            tahun: "2020 Januari 3",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "2", "d", "7", "60", "h",
            ],
        },
        {
            id: 3,
            judul: "Falling, Trevor Daniel",
            link: "https://www.youtube.com/watch?v=f2KmX0ZmGB0",
            tahun: "2020",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "2", "d", "7", "60", "h",
            ],
        },
        {
            id: 2,
            judul: "Make You Mine, PUBLIC",
            link: "https://www.youtube.com/watch?v=kExE86VPJS0",
            // images: [
            //     // "/music/358.mp3",
            // ],
            tahun: "2014",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "3", "a", "8", "60", "h",
            ],
        },
        {
            id: 1,
            judul: "Death Bed, powfu, beabadoobee",
            link: "https://www.youtube.com/watch?v=YefncL4TagU",
            // images: [
            //     // "/music/1.mp3",
            //     // "https://drive.google.com/file/d/1JBA0Nrp1Dr316eD_gmDLmA0okOMn_sUa/view?usp=drive_link",
            //     // "https://drive.google.com/file/d/1JBA0Nrp1Dr316eD_gmDLmA0okOMn_sUa/view?usp=sharing",
            //     // "https://drive.google.com/uc?export=download&id=1JBA0Nrp1Dr316eD_gmDLmA0okOMn_sUa",
            //     "https://drive.google.com/file/d/1JBA0Nrp1Dr316eD_gmDLmA0okOMn_sUa/view",
            // ],
            tahun: "2019?",
            added: "25 Maret 2020",
            playlist : [
                "b",
                "2", "d", "8", "60", "h",
            ],
        },
    ];

    return NextResponse.json(data);
}