// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjKr9JtjjJhldmP3NzUQq23Z7w7Yz3QMo',
    appId: '1:734061247705:web:d098d767648e98a13bd2c8',
    messagingSenderId: '734061247705',
    projectId: 'traveljoy-81ef6',
    authDomain: 'traveljoy-81ef6.firebaseapp.com',
    storageBucket: 'traveljoy-81ef6.firebasestorage.app',
    measurementId: 'G-769WWSG1P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8ev48lZwTQbTMZFRF_kWV4YGuaE3WGA',
    appId: '1:734061247705:android:26a710ef473716513bd2c8',
    messagingSenderId: '734061247705',
    projectId: 'traveljoy-81ef6',
    storageBucket: 'traveljoy-81ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsan11p1Oj5uUCdN0dDOFMA4hLNHtqJs',
    appId: '1:734061247705:ios:040e0f6546e0fb033bd2c8',
    messagingSenderId: '734061247705',
    projectId: 'traveljoy-81ef6',
    storageBucket: 'traveljoy-81ef6.firebasestorage.app',
    iosBundleId: 'com.bekup.traveljoy',
  );
}
